export const AlignItems = [ 
  'stretch'
    , 'center'
    , 'flex-start'
    , 'flex-end'
    , 'baseline'
    , 'safe stretch'
    , 'safe center'
    , 'safe flex-start'
    , 'safe flex-end'
    , 'safe baseline'
    , 'unsafe stretch'
    , 'unsafe center'
    , 'unsafe flex-start'
    , 'unsafe flex-end'
    , 'unsafe baseline'
    , 'initial'
    , 'inherit']

export const JustifyContent = [ 
  'flex-start'
    , 'flex-end'
    , 'center'
    , 'space-between'
    , 'space-around'
    , 'space-evenly'
    , 'safe flex-start'
    , 'safe flex-end'
    , 'safe center'
    , 'safe space-between'
    , 'safe space-around'
    , 'safe space-evenly'
    , 'unsafe flex-start'
    , 'unsafe flex-end'
    , 'unsafe center'
    , 'unsafe space-between'
    , 'unsafe space-around'
    , 'unsafe space-evenly'
    , 'initial'
    , 'inherit']

export const AlignContent = [ 
  'normal'
    , 'start'
    , 'flex-start'
    , 'end'
    , 'flex-end'
    , 'center'
    , 'space-between'
    , 'space-around'
    , 'space-evenly'
    , 'strech'
    , 'safe normal'
    , 'safe start'
    , 'safe flex-start'
    , 'safe end'
    , 'safe flex-end'
    , 'safe center'
    , 'safe space-between'
    , 'safe space-around'
    , 'safe space-evenly'
    , 'safe strech'
    , 'unsafe normal'
    , 'unsafe start'
    , 'unsafe flex-start'
    , 'unsafe end'
    , 'unsafe flex-end'
    , 'unsafe center'
    , 'unsafe space-between'
    , 'unsafe space-around'
    , 'unsafe space-evenly'
    , 'unsafe strech'
    , 'initial'
    , 'inherit' ]

export const FlexDirection = ['row', 'row-reverse', 'column', 'column-reverse']

export const FlexWrap = ['wrap', 'nowrap', 'wrap-reverse'];